canonical: http://profiles.ihe.net/QRPH/VRDR
title: "Vital Records Death Reporting (VRDR) FHIR Implementation Guide"
description: This profile defines multiple approaches to capturing death reporting information from provider systems, including messaging, document exchange, and an RFD-based approach that specifies derivation of source content from a medical summary document along with requirements for form filler content and form manager handling of content. The profile additionally defines the transactions and documents that may be exchanged between jurisdictions and national statistics agencies.
FSHOnly: false
applyExtensionMetadataToRoot: false
id: ihe.qrph.vrdr
name: IHE_QRPH_VRDR
status: draft
version: 0.0.1-current
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
#date: 2022-01-02
publisher:
  name: IHE Quality, Research and Public Health Technical Committee
  url: https://www.ihe.net/ihe_domains/quality_research_and_public_health/
  email: iheqrphtech@ihe.net
contact:
  - name: IHE Quality, Research and Public Health Technical Committee
    telecom:
      - system: email
        value: iheqrphtech@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
#  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources

dependencies:
  ihe.iti.pdqm: 
    id: ihepdqm
    uri: https://profiles.ihe.net/ITI/PDQm/ImplementationGuide/ihe.iti.pdqm
    version: 3.0.x
  hl7.fhir.us.vr-common-library: 
    version: 2.0.0 
    id: hl7fhirusvrcommonlibrary
  ihe.pcc.odh: 
    id: ihepccodh
    version: current 

pages:
  index.md:
    title: Home
  credits.md:
    title: Credits
  background.md:
    title: Background
  scope_of_the_vrdr_fhir_ig.md:
    title: Scope of the VRDR IG
  usage.md:
    title: Usage
  conformance.md:
    title: Conformance
  artifacts.html:
    title: Artifacts Summary
  vrdr_forms_mapping.md:
    title: VRDR Forms Mapping
  DeathRecordDataDictionary.md:
    title: Death Record Data Dictionary
  MortalityRosterDataDictionary.md:
    title: Mortality Roster Data Dictionary
  downloads.md:
    title: Download Specification
  change_log.md:
    title: Change Log
  content-transitions.md:
    title: Content Transitions 
menu:
  Home:
    Home: index.html
    Background: background.html
    Scope: scope_of_the_vrdr_fhir_ig.html
    Credits: credits.html
  Implementer Guidance:
    Usage Notes: usage.html
    Conformance: conformance.html
    Death Record Data Dictionary: DeathRecordDataDictionary.html
    Mortality Roster Data Dictionary: MortalityRosterDataDictionary.html
    IJE Mapping to FHIR (csv):  IJE_File_Layouts_and_FHIR_Mapping_24-06-21.csv
    IJE Mapping to FHIR (xlsx): IJE_File_Layouts_and_FHIR_Mapping_24-06-21.xlsx
    Forms Mapping: vrdr_forms_mapping.html
  Artifacts: artifacts.html
  Changes:
    Change Log: change_log.html
    STU2.2 to STU3 Changes: content-transitions.html
  Downloads: downloads.html

groups:
  DecedentDemographics:
    name: Decedent Demographics
    description: Demographic data includes information about related persons (Mother, Father, and Spouse) and social determinants such as education level. The information in this profile group are provided by a decedent informant.
    resources:
    - Decedent
    - DecedentAge
    - DecedentEducationLevel
    - DecedentMother
    - DecedentFather
    - DecedentSpouse
    - DecedentMilitaryService
    - DecedentUsualWork
  RecordLinkages:
    name: Vital Records Linkages
    description: These profiles support exchange of vital records identifiers for events that are related to the decedent.  Jurisdictions may provide linkages to birth records for all deaths within the first year of life, and linkages to birth or fetal death records when the for pregnancy-related events within one year of death. 
    resources:
    - BirthRecordIdentifier
    - BirthRecordIdentifierChild
    - FetalDeathRecordIdentifier
  DeathInvestigation:
    name: Death Investigation
    description: Data obtained during the course of investigating a death. Many of these items are conditionally present in a death certification transaction depending on whether or not an autopsy was performed, an injury incident occurred, or a transportation event was involved. The details on the pronouncement performer can be provided using USCore Practitioner profile.
    resources:
    - AutopsyPerformedIndicator
    - DeathDate 
    - DecedentPregnancyStatus
    - DeathLocation
    - ExaminerContacted
    - InjuryLocation
    - InjuryIncident 
    - SurgeryDate
    - TobaccoUseContributedToDeath 
  DeathCertification:
    name: Death Certification
    description: Data related to the primary concern of the VRDR IG, Death Certification. In this group, the causes of death and the causal pathway are documented and attested to by a death certifier (coroner or medical examiner).
    resources:
    - Certifier
    - CauseOfDeathPart1
    - CauseOfDeathPart2
    - DeathCertification 
    - MannerOfDeath 
  DecedentDisposition:
    name: Decedent Disposition
    description: Data related to the disposition of the decedents remains. The data in this profile group is typically provided by the funeral home performing the disposition services. The content of this profile group is authenticated by the funeral home director. Additional content can be included using standard USCore profiles, and can be included to specify the Funeral Home Director, the Licensee, and the Mortician.
    resources:
    - DispositionLocation
    - DecedentDispositionMethod
    - FuneralHome
    - Mortician 
  CodedObservations:
    name: Coded Observations
    description: Coded Observations based on the submitted death record.
    resources:
    - ActivityAtTimeOfDeath
    - AutomatedUnderlyingCauseOfDeath
    - ManualUnderlyingCauseOfDeath
    - RecordAxisCauseOfDeath
    - EntityAxisCauseOfDeath
    - PlaceOfInjury
    # - StructureDefinition/vrdr-coded-race-and-ethnicity
    - CodingStatusValues
  DocumentsAndBundles:
    name: Bundles and Compositions
    description: Bundles and Compositions used to transmit death record content.
    resources:
    - DeathCertificate
    - DeathCertificateDocument 
    - CauseOfDeathCodedContentBundle
    - DemographicCodedContentBundle
    - IndustryOccupationCodedContentBundle
    - MortalityRosterBundle

  Entensions:
    name: Extensions 
    description: Extensions 
    resources:
    - AliasStatus
    - FilingFormat
    - StateSpecificField
    - NVSSSexAtDeath
    - SpouseAlive
    - ReplaceStatus
    - PractitionerRole
  
  CodeSystems:
    name: CodeSystems
    description: CodeSystems 
    resources:
    - ActivityAtTimeOfDeathCS
    - DateOfDeathDeterminationMethodsCS
    - DeathPregnancyStatusCS
    - DocumentSectionCS
    - FilingFormatCS
    - IntentionalRejectCS
    - LocationTypeCS
    - ObservationsCS
    - ComponentCS
    - OrganizationTypeCS
    - ReplaceStatusCS
    - SuperMicarPlaceOfInjuryCS
    - SystemRejectCS
    - TransaxConversionCS

  ValueSets:
    name: ValueSets
    description: ValueSets 
    resources: 
    - AdministrativeGenderVS
    - CertifierTypesVS
    - IntentionalRejectVS
    - SystemRejectVS
    - TransaxConversionVS
    - ActivityAtTimeOfDeathVS
    - ICD10CausesOfDeathVS
    - ContributoryTobaccoUseVS
    - DateOfDeathDeterminationMethodsVS
    - DeathCertificationEventVS
    - DeathCertificationEventMaxVS
    - DeathPregnancyStatusVS
    - FilingFormatVS
    - MannerOfDeathVS
    - MethodOfDispositionVS
    - PlaceOfDeathVS
    - PlaceOfInjuryVS
    - PlaceOfInjuryOtherVS
    - ReplaceStatusVS
    - SpouseAliveVS
    - TransportationIncidentRoleVS
    - vrdr-edit-bypass-01-vs
    - vrdr-edit-bypass-012-vs
    - vrdr-edit-bypass-0124-vs

  ConceptMaps:
    name: ConceptMaps
    description: ConceptMaps 
    resources: 
    - ActivityAtTimeOfDeathCM
    - AdministrativeGenderCM
    - CertifierTypesCM
    - ContributoryTobaccoUseCM
    - DeathPregnancyStatusCM
    - EditBypass01CM
    - EditBypass012CM
    - EditBypass0124CM
    - FilingFormatCM
    - IntentionalRejectCM
    - MannerOfDeathCM
    - MethodOfDispositionCM
    - PlaceOfDeathCM
    - PlaceOfInjuryCM
    - ReplaceStatusCM
    - SpouseAliveCM
    - SystemRejectCM
    - TransaxConversionCM
    - TransportationIncidentRoleCM

  ExampleDeathRecord:
    name: Example Death Record Submission
    description: Example of a complete Death Record Submission 
    resources:
    - DeathCertificateDocument-UT-1
    - DeathCertificateUT-Example1
    - DecedentUT-Example1 
    - InputRaceAndEthnicityUT-Example1
    - PractitionerUT-Certifier
    - PractitionerUT-Pronouncer
    - BirthRecordIdentifierUT-Example1 
    - EducationUT-Example1
    - FatherUT-Example1
    - MotherUT-Example1
    - AutopsyPerformedIndicatorUT-Example1
    - CauseOfDeathPart1UT-Example1 
    - DeathDateUT-Example1
    - DeathLocationUT-Example1 
    - AgeUT-Example1 
    - DispositionMethodUT-Example1 
    - DispositionLocationUT-Example1
    - UsualWorkUT-Example1
    - MilitaryServiceUT-Example1
    - PregnancyUT-Example1 
    - ExaminerContactedUT-Example1 
    - FuneralHomeUT-Example1
    - InjuryIncidentUT-Example1 
    - MannerOfDeathUT-Example1 
    - TobaccoUseUT-Example1 
    - ProcedureDeathCertificationUT-Example1
    - EmergingIssuesUT-Example1

  ExampleBundles:
    name: Other Example Bundles
    description: Example Death Certificate, Coded Content, and Mortality Roster Bundles
    resources:
    - CauseOfDeathCodedContentBundle-Example1
    - DemographicCodedContentBundle-Example1
    - IndustryOccupationCodedContentBundle-Example1
    - MortalityRosterBundle-Example1
    - DeathCertificateDocument-Example1
    - DeathCertificateDocument-Example2

  OtherExamples:
    name: Other Example Instances 
    description: Other Example instances illustrating various aspects of the profiles.
    resources:
    - DeathCertification-Example1
    - DeathCertification-Example2  
    - AutopsyPerformedIndicator-Example1
    - BirthRecordIdentifier-Example1
    - BirthRecordIdentifierChild-Example1
    - FetalDeathRecordIdentifier-Example1
    - CauseOfDeathPart1-Example1
    - CauseOfDeathPart1-Example2
    - CauseOfDeathPart2-Example1
    - Certifier-Example1
    - AutomatedUnderlyingCauseOfDeath-Example1
    - RecordAxisCauseOfDeath-Example1
    - RecordAxisCauseOfDeath-Example2
    - EntityAxisCauseOfDeath-Example1
    - EntityAxisCauseOfDeath-Example2
    - EntityAxisCauseOfDeath-Example3
    - EntityAxisCauseOfDeath-Example4
    - ManualUnderlyingCauseOfDeath-Example1
    - PlaceOfInjury-Example1
    - ActivityAtTimeOfDeath-Example1
    - CodedRaceAndEthnicity-Example1
    - InputRaceAndEthnicity-Example1
    - CodingStatusValues-Example1
    - DeathCertificate-Example1
    - DeathCertificate-Example2
    - DeathDate-Example1
    - DeathDate-Example2
    - DeathDate-Example3
    - DeathDate-Example4
    - DeathLocation-Example1
    - DeathLocation-Example2
    - DeathLocation-Example3
    - Decedent-Example3
    - Decedent-Example2
    - Decedent-Example1
    - DecedentAge-Example1
    - DecedentDispositionMethod-Example1
    - Mortician-Example1
    - DispositionLocation-Example1
    - DecedentEducationLevel-Example1
    - DecedentMilitaryService-Example1
    - DecedentPregnancyStatus-Example1
    - DecedentUsualWork-Example1
    - DecedentUsualWork-Example2
    - EmergingIssues-Example1
    - ExaminerContacted-Example1
    - DecedentFather-Example1
    - DecedentMother-Example1
    - DecedentSpouse-Example1
    - FuneralHome-Example1
    - InjuryIncident-Example1
    - InjuryIncident-Example2
    - InjuryLocation-Example1
    - MannerOfDeath-Example1
    - SurgeryDate-Example1
    - TobaccoUseContributedToDeath-Example1
    - location-death-vr-atlanta-ga-a-freeman
    - location-injury-vr-atlanta-ga-a-freeman
    - practitioner-vital-records-janet-seito
    - procedure-death-certification-vr-a-freeman
    - us-core-patient-vr-a-freeman
    - Pronouncer-Example1
    - Certifier-Example2-no-NPI

# ToDO delete this oid root when you delete everything 
  auto-oid-root: 2.16.840.1.113883.4.642.40.10

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher